# Generated by Django 6.0.6 on 2026-06-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(max_length=100)),
                ("state_country", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("duration", models.CharField(max_length=50)),
                ("best_time", models.CharField(max_length=100)),
                ("places_covered", models.TextField()),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="trip_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
