# Generated by Django 6.0.6 on 2026-06-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="state_country",
            new_name="state_or_country",
        ),
    ]
