# Generated by Django 6.0.6 on 2026-06-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
